#!/usr/bin/env node

var model = require('../../../database/models');
var utils = require('../../utils/responses');

function getProducts(req, res, ops){

    model.Product.find(null, '-_id -_v', (err, doc) =>{

        if(err) {
            console.log('[ERROR]products/getProducts:', err);
            utils.jsonBadResponse(res, 404);
            return
        }

        utils.jsonResponse(res, 200, doc);

    })
    
}

function getProductDetails(req, res, ops){
    //var products = db.collection('products');

    //console.log('getOneProduct:', ops);

    model.Product.findOne({ id: ops.id }, '-_id -__v', (err, doc) => {

        console.log('getOneProduct:',doc);

        if( err || doc == null){

            console.log('[ERROR]products/getOneProduct: Error', err );
            utils.jsonBadResponse(res, 404);

        } else {

            console.log('products/getOneProduct: El elemento fue encontrado', doc);
            utils.jsonResponse(res, 200, doc );

        }

    })
    
}

function getProductsByCategory(req, res, ops){

    //console.log('ops',ops)

    model.Product.find({ category: ops.category }, '-_id -_v', (err, doc) =>{
        if(err || doc === null) {
            console.log('[ERROR]products/getProductsByCategory:', err);
            utils.jsonBadResponse(res, 404);
            return
        }

        //console.log('doc',doc)
        utils.jsonResponse(res, 200, doc);

    })
}

function getCovers(req, res, ops){
    //var products = db.collection('products');

    model.Cover.find(null, '-_id -_v', (err, doc) =>{

        if(err) {
            console.log('[ERROR]products/getProducts:', err);
            utils.jsonBadResponse(res, 404);
            return
        }

        utils.jsonResponse(res, 200, doc);

    })
    
}

function getTodayNumber(req, res, ops){
    //var products = db.collection('products');

    model.TodayNumber.find({ visible: true }, '-_id -_v',(err, doc) =>{

        if(err) {
            console.log('[ERROR]products/getTodayNumber:', err);
            utils.jsonBadResponse(res, 404);
            return
        }

        utils.jsonResponse(res, 200, doc);

    })
    
}

module.exports = {
     getProducts
    ,getProductDetails
    ,getProductsByCategory
    ,getCovers
    ,getTodayNumber
}
