#!/usr/bin/env node

var auth = require('./routes/auth');
var products = require('./routes/products');

function post(req, res, ops){
    
    if ( req.url === '/mobileLogin' )
        auth.mobileLogin( req, res, ops );

    else
    if( req.url === '/mobileRegister' )
        auth.mobileRegister( req, res, ops );

    else
    if ( req.url === '/searchProduct' )
        products.searchProduct( req, res, ops );

    else
    if ( req.url === '/setProduct' )
        products.setProduct( req, res, ops );

    else
    if ( req.url === '/updateProduct' )
        products.updateProduct( req, res, ops );

    else
    if( req.url === '/setCover' )
        products.setCover( req, res, ops );

    else
    if( req.url === '/setTodayNumber')
        products.setTodayNumber( req, res, ops );

    else
    if( req.url === '/updateProfile' )
        auth.updateProfile( req, res, ops );

    else
        res.end();
    
}



module.exports = post;
