#!/usr/bin/env node

var load = require('./load');
var auth = require('../utils/access');
var responses = require('../utils/responses')

function static( req, res ){
    var use = false;
    
    if( req.url === '/' ) {
        
        load.loadHTML( './view/html/home.html', req, res );
        use = true;

    } else if(req.url === '/new-product'){

        if( auth.checkForAccess(req.headers.cookie) ){
            load.loadHTML( './view/html/new_product.html', req, res );
        } else {
            responses.redirect(res, 302, '/ingresar' )
        }
        
        use = true;

    } else if( req.url === '/ingresar'){

        load.loadHTML( './view/html/login.html', req, res );
        use = true;

    } else if( req.url === '/registro'){

        load.loadHTML( './view/html/signup.html', req, res );
        use = true;

    }





    /**@Scripts */
    else if( req.url === '/js/home.js') {

        load.loadJS( './view/js/home.js', req, res );
        use = true;

    } else if( req.url === '/js/ws.js') {

        load.loadJS( './view/js/socket.io.js', req, res );
        use = true;
    } else if( req.url === '/js/auth.js') {

        load.loadJS( './view/js/auth.js', req, res );
        use = true;
    }




    

    /**@Styles */
    else if( req.url === '/css/home.css' ) {

        load.loadCSS( './view/css/home.css', req, res );
        use = true;

    }

    return use;

}

module.exports = static;