#!/usr/bin/env node

var products = require('./routes/products');
var messages = require('./routes/messages')
var contacts = require('./routes/contacts');
var c_urlparser = require('../../build/Release/urlparser.node');


function get(req, res, ops){

    var use = false;

    var url = c_urlparser.parse(req.url);

    
    /**@Products */
    if(url.path === '/getProducts') {

        products.getProducts(req, res, url);
        use = true;

    }

    else if(url.path === '/getProductDetails') {

        products.getProductDetails(req, res, url);
        use = true;

    }

    else if(url.path === '/getProductsByCategory') {
        products.getProductsByCategory(req, res, url);
        use = true;
    }

    else if(url.path === '/searchProduct'){
        products.searchProduct(req, res, url);
        use = true;
    }


    /**@Messages */
    else if( url.path === '/getMessages' ){
        messages.getMessages(req, res, url);
        use = true;
    }

    else if( url.path === '/getNotifications' ){
        messages.getMessageNotifications(req, res, url);
        use = true;
    }

    else if( url.path === '/getCovers' ){
        products.getCovers( req, res, url );
        use = true;
    }

    else if( url.path === '/getTodayNumber' ){
        products.getTodayNumber( req, res, url );
        use = true;
    }


    /**@Contacts */
    else if(url.path === 'searchContact') {
        contacts.searchContact(req, res, url);
    }

    return use;
    
}

module.exports = get;
