#!/usr/bin/env node

var route = require('./routes/routes');
var products = require('./routes/products');
var categories = require('./routes/categories');
var contacts = require('./routes/contacts');
var c_urlparser = require('../../build/Release/urlparser.node');


function get(req, res, ops){


    var url = c_urlparser.parse(req.url);

    
    if(url.path === '/'){

        route.home(req, res);

    }
    
    else if(url.path === '/getProducts') {

        products.getProducts(req, res, url);

    }

    else if(url.path === '/setProduct') {

        products.setProduct(req, res, url);

    }

    else if(url.path === '/updateProduct') {

        products.updateProduct(req, res, url);

    }

    else if(url.path === '/getCategories') {

        categories.getCategories(req, res, url);
    }

    else if(url.path === '/setCategory') {
        categories.setCategory(req, res, url);
    }


    /**@Contacts */
    else if(url.path === 'searchContact') {
        contacts.searchContact(req, res, url);
    }

    else {

        //res.writeHead(200);
        res.end();

    }
    
}

module.exports = get;
