#! /usr/bin/env node

var jwt = require('./jwt');
var cookie = require('cookie');
const { use } = require('chai');



function checkForAccess(incomingCookie){

    var access = false;

    var parsedCookie = cookie.parse(String(incomingCookie));
        
    "use strict";
    if( parsedCookie.token || parsedCookie.token ){

        console.log('parsedCookie.token', parsedCookie.token)

        var decodedToken = jwt.decodeToken(parsedCookie.token)

        console.log('token',decodedToken);

        if( decodedToken ){
            access = true;
        }
    }
        
    return access;

}

module.exports = {
    checkForAccess
}