#!/usr/bin/env node

/**     Utils     */

var nanoid = require('nanoid');


function jsonResponse(res, status, jsondata){
    console.log('jsonResponse:','status ' + status);
    res.writeHead(status);
    res.write(JSON.stringify(jsondata));
    res.end();
}



function jsonBadResponse(res, status){
    console.log('[BAD!]jsonBadResponse:','status ' + status);
    res.writeHead(status);
    res.end();
}



function createDatabaseUserInfoObject(req, body, hash){
    var myObject = {
        user_id: nanoid(),
        email: body.email,
        username: body.username,
        password: hash,
        image: null,
        role: 0,
        user_ip: req.connection.remoteAddress,
        contrib: true,
        timestamp: Date()
    };

    console.log('userInfoObject', myObject);

    return myObject;
}



function handleCredentials(client, server){

}



module.exports = {
    jsonResponse,
    jsonBadResponse,
    handleCredentials,
    createDatabaseUserInfoObject
}