#! usr/bin/env node

var model = require('../../database/models');

/** Websockets */
function websockets(io){

    io.on('connection', socket => {

        var id = socket.handshake.query['id'];
        //console.log('user_id', id)
        
        socket.leave(socket.id);//leaving default room
        socket.join(id);//joining to custom room
        
        //console.log('Websockets:', 'connected');

        socket.on('message', function(data) {
            
            //console.log('websockets', data);
            data.timestamp = new Date();

            var message = new model.Message(data);
            setMessage(socket, message);

            var roomClients = io.sockets.adapter.rooms[data.to_id];
            console.log('Room clients:', roomClients);//Querying clients in a given room

            io.to(data.to_id).emit('message', data);

            socket.emit('message', data);

        });
        
    });

}

function setMessage(socket, message){
    message.save((err, doc) => {
        if (err) {
            socket.emit('error','mensaje no guardado');
        } else {
            console.log('Websockets/index: El mensaje se guardO correctamente', doc);
        }
    });

}

module.exports = websockets;