#! usr/bin/env node

/** Websockets */
function websockets(io){

    io.on('connection', socket => {

        //console.log('io',socket.request.connection)
        console.log('websockets', 'connected');
        io.emit('message', { username: 'Server',type: 'server', message: 'Mensaje automático del servidor', timestamp: Date()});

        socket.on('message', function(data) {
            
            console.log('websockets', data);
            data.timestamp = new Date();
            io.emit('message', data);

        });
        
    });

}

module.exports = websockets;